# Generated by Django 2.0.5 on 2018-05-25 10:32

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('surname', models.CharField(max_length=100)),
                ('job_title', models.CharField(blank=True, choices=[('developer', 'Developer'), ('manager', 'Manager')], max_length=250)),
                ('programming_language', models.CharField(blank=True, choices=[('go', 'Golang'), ('python', 'Python'), ('java', 'Java')], max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(blank=True, choices=[('annual', 'Annual'), ('excused', 'Excused'), ('other', 'Other')], max_length=250)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('description', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('surname', models.CharField(max_length=100)),
                ('job_title', models.CharField(blank=True, choices=[('developer', 'Developer'), ('manager', 'Manager')], max_length=250)),
                ('manager_items', multiselectfield.db.fields.MultiSelectField(choices=[('house', 'House'), ('car', 'Car')], max_length=9)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='developer',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.Manager'),
        ),
    ]
