# Generated by Django 2.0.5 on 2018-05-25 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow', '0008_merge'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.Process')),
                ('leave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.Leave')),
            ],
            options={
                'verbose_name_plural': 'Leave process list',
            },
            bases=('viewflow.process',),
        ),
        migrations.CreateModel(
            name='LeaveTask',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('viewflow.task',),
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'permissions': [('can_approve_leave', 'Can approve leave form')]},
        ),
    ]
